
#include "cpu.h"

namespace dsemu::cpu {

OpCode opCodes[] = {
    {0x00, "NOP", NOP, 1},
    {0x01, "LD BC,nn", LD, 3, ATypeIR, {BC, NN}},
    {0x02, "LD (BC),A", LD, 1, ATypeRA, {BC, A}},
    {0x03, ""},
    {0x04, ""},
    {0x05, ""},
    {0x06, "LD B,n", LD, 2, ATypeIR, {B, N}},
    {0x07, ""},
    {0x08, "LD (nn),SP", LD, 3, ATypeRA, {NN, SP}},
    {0x09, "", LD, 3, ATypeRA, {NN, SP}},
    {0x0A, "", LD, 3, ATypeRA, {NN, SP}},
    {0x0B, "", LD, 3, ATypeRA, {NN, SP}},
    {0x0C, "", LD, 3, ATypeRA, {NN, SP}},
    {0x0D, "", LD, 3, ATypeRA, {NN, SP}},
    {0x0E, "", LD, 3, ATypeRA, {NN, SP}},
    {0x0F, "", LD, 3, ATypeRA, {NN, SP}},
    {0x10, "NOP", NOP, 1},
    {0x11, "LD BC,nn", LD, 3, ATypeIR, {BC, NN}},
    {0x12, "LD (BC),A", LD, 3, ATypeRA, {BC, A}},
    {0x13, ""},
    {0x14, ""},
    {0x15, ""},
    {0x16, "LD B,n", LD, 3, ATypeIR, {B, N}},
    {0x17, ""},
    {0x18, "LD (nn),SP", LD, 3, ATypeRA, {NN, SP}},
    {0x19, "", LD, 3, ATypeRA, {NN, SP}},
    {0x1A, "", LD, 3, ATypeRA, {NN, SP}},
    {0x1B, "", LD, 3, ATypeRA, {NN, SP}},
    {0x1C, "", LD, 3, ATypeRA, {NN, SP}},
    {0x1D, "", LD, 3, ATypeRA, {NN, SP}},
    {0x1E, "", LD, 3, ATypeRA, {NN, SP}},
    {0x1F, "", LD, 3, ATypeRA, {NN, SP}},
    {0x20, "NOP", NOP, 1},
    {0x21, "LD BC,nn", LD, 3, ATypeIR, {BC, NN}},
    {0x22, "LD (BC),A", LD, 3, ATypeRA, {BC, A}},
    {0x23, ""},
    {0x24, ""},
    {0x25, ""},
    {0x26, "LD B,n", LD, 3, ATypeIR, {B, N}},
    {0x27, ""},
    {0x28, "LD (nn),SP", LD, 3, ATypeRA, {NN, SP}},
    {0x29, "", LD, 3, ATypeRA, {NN, SP}},
    {0x2A, "", LD, 3, ATypeRA, {NN, SP}},
    {0x2B, "", LD, 3, ATypeRA, {NN, SP}},
    {0x2C, "", LD, 3, ATypeRA, {NN, SP}},
    {0x2D, "", LD, 3, ATypeRA, {NN, SP}},
    {0x2E, "", LD, 3, ATypeRA, {NN, SP}},
    {0x2F, "", LD, 3, ATypeRA, {NN, SP}},
    {0x30, "NOP", NOP, 1},
    {0x31, "LD BC,nn", LD, 3, ATypeIR, {BC, NN}},
    {0x32, "LD (BC),A", LD, 3, ATypeRA, {BC, A}},
    {0x33, ""},
    {0x34, ""},
    {0x35, ""},
    {0x36, "LD B,n", LD, 3, ATypeIR, {B, N}},
    {0x37, ""},
    {0x38, "LD (nn),SP", LD, 3, ATypeRA, {NN, SP}},
    {0x39, "", LD, 3, ATypeRA, {NN, SP}},
    {0x3A, "", LD, 3, ATypeRA, {NN, SP}},
    {0x3B, "", LD, 3, ATypeRA, {NN, SP}},
    {0x3C, "", LD, 3, ATypeRA, {NN, SP}},
    {0x3D, "", LD, 3, ATypeRA, {NN, SP}},
    {0x3E, "LD A, n", LD, 2, ATypeIR, {A, N}},
    {0x3F, "", LD, 3, ATypeRA, {NN, SP}},
};

}
